name: Lighthouse Audit

on:
  workflow_run:
    workflows: ["UI Tests"]
    types:
      - completed

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse Audit
        run: |
          sudo mkdir -p allure-report/lighthouse  
          lighthouse https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index --output=html --output-path=allure-report/lighthouse/lighthouse-report.html || true

      - name: Deploy Lighthouse Report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true


