name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker-compose up --exit-code-from regression || true

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history  
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          sudo docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Run Lighthouse Audit
        run: |
          docker run --rm -v $PWD:/home/chrome/reports --network="host" \
          lighthouse/lighthouse https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index --output=html --output-path=/home/chrome/reports/lighthouse-report.html

      - name: Copy Lighthouse Report
        run: |
          sudo mkdir -p allure-report/lighthouse
          sudo cp ./lighthouse-report.html allure-report/lighthouse/

      - name: Update Allure history
        run: |
          sudo cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true